---
title: "Handy Dirty Indices"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r setup, include=FALSE}
library(tidyverse)
library(DT)
library(plotly)
library(shiny)
library(stats)
library(forecast)
source("Handy_dirty_indices.R")

IndChoices <- df %>% dplyr::select_if(is.numeric) %>% names()

updatedf <- reactive( df %>% dplyr::select(!!! rlang::syms(input$Ind),"Date"))
updatets <- reactive( df %>% dplyr::select(!!! rlang::syms(input$Ind)) %>% ts(frequency = 52, start = c(2003, 6)))
```


Column {.sidebar}
------------------------------------------------------------------
```{r}
selectInput(inputId = "Ind",label = "Indices", choices = IndChoices)
sliderInput(inputId = "h",label = "Number of weeks to forecast ?", value = 52, min = 1, max = 260)
```

Column {.tabset}
------------------------------------------------------------------

### indices
```{r}
renderPlotly({
p <- updatedf() %>% ggplot(aes(x=Date,y=!! rlang::sym(input$Ind))) +
        geom_line() + ggtitle("Plot of the  Time-Series") + theme_bw() + scale_y_continuous(breaks=seq(-60000,60000,10000))

    ggplotly(p)
})
```

### Decomposition
```{r}
renderPlot({
updatets() %>% fdecomp2() %>% autoplot() + xlab("") + ylab("") + 
    ggtitle("Decomposition plot of the  Time-Series") + 
    theme_bw()
})
```


### Forcast
```{r}
renderPlot({
updatets() %>% fstlf(input$h) %>% autoplot() + 
    ggtitle("Forecasting the Time-Series") + 
    theme_bw()
})
```


### Residuals
```{r}
renderPlot({
updatets() %>% fstlf(input$h) %>% checkresiduals(theme = theme_bw())
  
})
```


### Data
```{r}
renderDT(
  updatedf(), rownames = F, extensions = 'Buttons', filter="top", editable=T,
  options = list(
    dom = 'Blfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'),
    lengthMenu = list(c(10,50,100,-1),c(10,50,100,"All"))
  )
)
```




